rust-embedded/cortex-m-quickstart

Cargo.toml
Without debug information, `tbreak cortex_m_rt::reset_handler` does not work:
rustc does not include the Rust support script directive, gdb does not load it,
and breakpoints can only be set on functions using their full mangled name.
=> Include debug information in release builds

.cargo/config, Cargo.toml, src/lib.rs
with this `xargo run` will build the program *and* immediately start a GDB
session.
=> set default runner to arm-none-eabi-gdb

.gdbinit
simply `step` after the `load` command. This should just work now that we are
using cortex-m-rt v0.2.2
=> gdbinit: don't reset the microcontroller

.gdbinit
This happens automatically when openocd sets up the tpiu; see openocd manual 16.5.4.
=> Remove 'monitor tpiu itm port 0 on' from .gdbinit

.gdbinit
This reverts commit f88a44fd78ed111577e50d8765068ea9bf9919eb.
It's required on OpenOCD 0.10.0
cc @adamgreig I have been trying the latest quickstart version and ITM doesn't
work unless I add back this 'itm port 0 on' command. It seems to latch though
because if I run the command once then I don't need it anymore (unless I power
off the target device)
=> Revert "Remove 'monitor tpiu itm port 0 on' from .gdbinit"

Xargo.toml, examples/allocator.rs, src/examples/_6_allocator.rs
Now, that rust switched to https://github.com/rust-lang-nursery/compiler-builtins, is there any reason to point to this repository in Xargo.toml? I tried and my projects working fine using compiler-builtins from rust-src.
=> Build compiler-builtins from rust source instead of github repository.

.gdbinit
this change turns this:
``` console
(gdb) x/4 0x200003f0
0x200003f0 <_ZN3app2XS17h4b49405669958fd2E+1008>:       0x20000400      0x080004f5      0x00000000      0x00000001
```
into this:
``` console
(gdb) x/4 0x200003f0
0x200003f0 <app::XS+1008>:      0x20000400      0x080004f5      0x00000000      0x00000001
```
=> gdbinit: print demangled symbols by default

Cargo.toml
This is due to #[lang = "panic_fmt"] -> #[panic_implementation] breakage
=> Update panic-semihosting dependency to 0.3.0

build.rs
The current `build.rs` contains
```rust
println!("cargo:rerun-if-changed=build.rs");
println!("cargo:rerun-if-changed=memory.x");
```
This causes the build script to be re-run if (and *only if*) `build.rs` or `memory.x` change. The line for `build.rs` is redundant: the Cargo guide [says](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) the build script is always rerun when `build.rs` changes, so we can drop that line.
The remaining line caused me a bit of confusion when adding other functionality to my project's build script, before I realised it tells Cargo to *only* rerun the build script when `memory.x` changes, as opposed to the default behaviour which is to rerun it on every build. The comment helps clarify the point of this line, so if users …
=> Clarify purpose of rerun-if-changed in build.rs

README.md
As Cargo.toml now includes edition = "2018", it won't build with rust 1.30-stable. 1.31-stable will be the first stable version to have the edition feature enabled. (See https://internals.rust-lang.org/t/rust-2018-release-schedule-and-extended-beta/8076 for details.)
At the same time, remove the remark about 1.30-beta not being out yet, as it's out by now.
=> Update rust version requirements in README.md

memory.x
We're using a STM32F429 and wanted to move stuff around in memory, notably put stack+data into CPU coupled memory, and put framebuffers for the integrated LCD controller into the normal SRAM.
Getting this right while not completely overriding the default `link.x` was quite tricky (especially finding the `INSERT AFTER` life-saver...) so I thought an example would not hurt here.
It should probably also be mentioned in other places (book/...)?
=> Add example moving .bss data into custom memory

openocd.gdb
Extended remote allows a lot more features like attaching and detaching and much more fine-grained execution options. If a gdbserver implementation supports it (and OpenOCD sure does) it should be preferred over `remote`.
=> Default to extended-remote instead of remote mode

src/main.rs
Fixes #50 but is only a workaround until it is fixed in the compiler
=> Workaround for loop {} until it is fixed

examples/test_on_host.rs
It's surprisingly difficult to find an example of how to write tests that run on the host machine when using `no_std`.
This PR adds an example of how to get tests compiling and running when using the quickstart.
It's based heavily on this blog.
https://os.phil-opp.com/unit-testing/
=> Add example of writing tests that run on host machine

openocd.gdb
I noticed as I was going through the rust-embedded book that I was receiving the following warning when running the compiled code through GDB (via `cargo run`):
```
Function "UserHardFault" not defined.
```
It looks like [this was renamed](https://github.com/rust-embedded/cortex-m-rt/pull/144) and the template just didn't get updated. This PR just updates the associated default break point to match the change.
=> Adjust the default breakpoint name to match cortex-m-rt pull #144

examples/device.rs
NVIC wasn't imported from the stm32f30x crate
=> added missing import

openocd.gdb
Just a little something to make the live for beginners easier.
=> add openocd.gdb hint how to print panic immediatly

.gitignore, .vscode/README.md, .vscode/launch.json, .vscode/tasks.json, README.md
I'm not sure if the project is interested in this, but I couldn't figure out any way to keep my VS Code template separate from the cortex-m-quickstart template.
This patchset adds VS Code debug configurations/examples for both QEMU and OpenOCD (lm3s6965evb and stm32f303vct6 respectively).
I couldn't find an SVD file for the Texas Instruments controller, so there's no in editor peripheral viewer for that one.
=> VS Code Support

.gitignore
Ignoring the .vscode/ directory is good default behavior,
but it's probably best to track the files that define build tasks, debug
configs, documentation, and any system view description files.
The gitignore.io sample takes the same approach.
https://www.gitignore.io/api/visualstudiocode
> ```
> .vscode/*
> !.vscode/settings.json
> !.vscode/tasks.json
> !.vscode/launch.json
> !.vscode/extensions.json
> ```
The VS Code team is on the record as committing these files as well.
> We in the VS Code team share debug and task specific settings as well because we want our team to have the same set of debug targets and task targets for VS Code.
https://stackoverflow.com/a/32979933/3198973
Even people who vehemently argue that .vscode shouldn't be tracked, agree
that complex debug configs should be …
=> Track launch.json, tasks.json, md & svd files

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json
Adds the following build tasks for VS Code:
- `clean`
- `--release`
- `--examples`
- `--examples --release`
It should be noted that `--examples` won't build successfully, because in general, you can't run `cargo build --examples` on projects generated from the quickstart.
It does trigger the correct behavior and I have tested these tasks on projects where it does build cleanly.
https://github.com/rubberduck203/stm32f3-discovery/blob/4933a160eee6ca53cc94c50d0470ea6e8ab03928/.vscode/tasks.json
=> VS Code build tasks

.vscode/tasks.json
My VSCode install wasn't showing the default build task. Based on the other ones, this seems to have fixed it.
=> Corrected default VSCode build task.

examples/allocator.rs, examples/crash.rs, examples/device.rs, examples/exception.rs, examples/hello.rs, examples/itm.rs, examples/panic.rs, examples/test_on_host.rs, src/main.rs
Replacing unidiomatic `extern crate` in case of importing of panic_ crates.
The appropriate PR to https://github.com/rust-embedded/book/ is [here](https://github.com/rust-embedded/book/pull/248).
=> Replace unidiomatic 'extern crate' to 'use x as _'

.cargo/config
Without this, the linker places some extra program header entries that can confuse flashing tools.
Many thanks to @jonas-schievink for pointing me to this flag in Matrix.
**How to reproduce the bug**
- `cargo generate --git https://github.com/rust-embedded/cortex-m-quickstart`
- change flash `ORIGIN = 0x00027000` in `memory.x`
- `cargo build`
- `llvm-objdump -x target/thumbv7em-none-eabihf/debug/repro`
Program header entries will look something like this:
```
Program Header:
PHDR off    0x00000034 vaddr 0x00020034 paddr 0x00020034 align 2**2
filesz 0x00000100 memsz 0x00000100 flags r--
LOAD off    0x00000000 vaddr 0x00020000 paddr 0x00020000 align 2**16
filesz 0x00000134 memsz 0x00000134 flags r--
LOAD off    0x00007000 vaddr 0x00027000 paddr 0x00027000 align 2**16
filesz 0x00000400 memsz …
```
=> Add --nmagic linker arg, for unaligned flash origin support.

.vscode/launch.json, .vscode/tasks.json
Using the equivalent command line as the task name caused some confusion.
Users were under the impression that they could use any valid cargo command as a preLaunchTask in the launch configurations.
=> Fixes #99: Disambiguates VSCode Tasks

.vscode/README.md, .vscode/extensions.json, .vscode/launch.json
RLS and its extension have been deprecated as rust-analyzer has become the official language server for Rust.
=> Recommend rust-analyzer vscode extension

.cargo/config.toml, build.rs
It's easy to forget about the hidden `.cargo/config.toml` file, and setting the linker flags in build.rs also means they can be changed without requiring a rebuild of everything, they are more robust to running the build from a location where `.cargo/config.toml` isn't picked up, and they make it easier to support different linker arguments for different crates or binaries.
Thanks to @Dirbaio for the suggestion!
=> Move link-arg setting from .cargo/config.toml to build.rs

Cargo.toml, examples/allocator.rs, examples/crash.rs, examples/device.rs, examples/exception.rs, examples/hello.rs
The allocator example is basically the same as [here](https://github.com/rust-embedded/embedded-alloc/blob/master/examples/global_alloc.rs).
The necessary change in the crash example is documented [here](https://docs.rs/cortex-m-rt/latest/cortex_m_rt/attr.exception.html#hardfault-handler).
=> Update crates and adapt example code
